# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Guazacapán spellchecker"
qda = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Guazacapán, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
qda = "TRANSLATE: A spellchecker for Guazacapán, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.xin-x-qda"

[windows]
system_product_code = "{E5DE46A1-AD85-46CF-959B-694CCF219BD4}_is1"

[package.speller]
name = "Guazacapán"
version = "0.1.0"

[package.grammar]
name = "Guazacapán"
version = "0.1.0"

[package.tts-text-proc]
name = "Guazacapán"
version = "0.1.0"
