template = "https://github.com/giellalt/template-lang-und"
rev_id = 245
template_sha = "6264a1351c6fd30e2a0f34d7ece4150965d960d8"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
