template = ""
rev_id = 70
template_sha = "ed1d5195c9d61fedd6150cd217179e4cbbfe8e23"

[replacements]
__LICENCE__ = "GPLv3"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
__REPO__ = "lang-xin-x-qda"
