template = ""
rev_id = 128
template_sha = "d3822979aa3293c4fa535cdebe16b2b39ffde39f"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
