template = ""
rev_id = 110
template_sha = "8ad9f0ef97f3aee03ef3eb9b1c8195cfd8338904"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
