template = ""
rev_id = 159
template_sha = "05d3c529289cf77947ecd4becc01d15560188456"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
