template = ""
rev_id = 176
template_sha = "c92a3e5f9990a7da698d2a35955696c64e8596cc"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
