template = ""
rev_id = 89
template_sha = "af8541df7c1e45fc9cc76282cc77195dbf8d95b6"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-xin-x-qda"
__UND2C__ = "qda"
__UNDEFINED__ = "Guazacap√°n"
__UND__ = "qda"
